CREATE TABLE HOUSES(
	HOUSEID INTEGER PRIMARY KEY,
	NAME TEXT,
	DESCRIPTION TEXT,
	REFRESHUNIT CHAR,
	REFRESHAMOUNT INTEGER,
	NEXTREFRESH DATETIME,
	CURRENTPHASE TEXT,
	CURRENTTURN INTEGER
);

CREATE TABLE USERS(
	USERID INTEGER PRIMARY KEY,
	NAME TEXT
);

CREATE TABLE CHORES (
	CHOREID INTEGER PRIMARY KEY,
	NAME TEXT,
	DESCRIPTION TEXT,
	HOUSEID INTEGER NOT NULL,
	OWNERID INTEGER NOT NULL,
	CLAIMED BOOLEAN,
	FOREIGN KEY (HOUSEID) REFERENCES HOUSES (HOUSEID),
	FOREIGN KEY (OWNERID) REFERENCES USERS (USERID)
);

CREATE TABLE OFFERS (
	OFFERID INTEGER PRIMARY KEY,
	HOUSEID INTEGER NOT NULL,
	ASKINGID INTEGER NOT NULL,
	RECEIVINGID INTEGER NOT NULL,
	STATUS TEXT,
	FOREIGN KEY (HOUSEID) REFERENCES HOUSES (HOUSEID),
	FOREIGN KEY (ASKINGID) REFERENCES USERS (USERID),
	FOREIGN KEY (RECEIVINGID) REFERENCES USERS (USERID)
);

CREATE TABLE PLACEMENTS (
	PLACEMENTID INTEGER PRIMARY KEY,
	USERID INTEGER NOT NULL,
	HOUSEID INTEGER NOT NULL,
	FUTURECODE INTEGER,
	PLACE INTEGER,
	FOREIGN KEY (HOUSEID) REFERENCES HOUSES (HOUSEID),
	FOREIGN KEY (USERID) REFERENCES USERS (USERID)
);

CREATE TABLE USERSTOHOUSES (
	USERID INTEGER,
	HOUSEID INTEGER,
	ISADMIN BOOLEAN,
	PRIMARY KEY (USERID,HOUSEID),
	FOREIGN KEY (HOUSEID) REFERENCES HOUSES (HOUSEID),
	FOREIGN KEY (USERID) REFERENCES USERS (USERID)
);

CREATE TABLE OFFEREDCHORES (
	OFFERID INTEGER,
	CHOREID INTEGER,
	OFFERSIDE CHAR,
	PRIMARY KEY (OFFERID,CHOREID),
	FOREIGN KEY (OFFERID) REFERENCES OFFERS (OFFERID),
	FOREIGN KEY (CHOREID) REFERENCES CHORES (CHOREID)
);

CREATE TABLE OFFEREDPLACEMENTS (
	OFFERID INTEGER,
	PLACEMENTID INTEGER,
	OFFERSIDE CHAR,
	PRIMARY KEY (OFFERID, PLACEMENTID),
	FOREIGN KEY (OFFERID) REFERENCES OFFERS (OFFERID),
	FOREIGN KEY (PLACEMENTID) REFERENCES PLACEMENTS (PLACEMENTID)
);

CREATE TABLE NOTIFICATIONS (
	NOTIFICATIONID INTEGER PRIMARY KEY,
	TITLE TEXT,
	DESCRIPTION TEXT,
	ISREAD BOOLEAN,
	USERID INTEGER,
	FOREIGN KEY (USERID) REFERENCES USERS (USERID)
);

CREATE TABLE REVERTPLACEMENTS (
	REVERTPLACEMENTID INTEGER PRIMARY KEY,
	REVERTTO INTEGER,
	PLACEMENTID INTEGER,
	FOREIGN KEY (REVERTTO) REFERENCES USERS (USERID),
	FOREIGN KEY (PLACEMENTID) REFERENCES PLACEMENTS (PLACEMENTID)
);
